apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_ENV: local
  APP_FAKER_LOCALE: en_US
  APP_FALLBACK_LOCALE: en
  # APP_KEY:
  APP_LOCALE: en
  APP_MAINTENANCE_DRIVER: file
  APP_NAME: Laravel
  APP_TIMEZONE: UTC
  APP_URL: https://meetup.mu
  ASSET_URL: https://meetup.mu
  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  BCRYPT_ROUNDS: "12"
  BROADCAST_CONNECTION: log
  CACHE_PREFIX: ""
  CACHE_STORE: database
  DB_CONNECTION: mysql
  DB_DATABASE: laravel
  DB_HOST: meetup-mysql
  DB_PASSWORD: password
  DB_PORT: "3306"
  DB_USERNAME: alex
  FILESYSTEM_DISK: local
  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug
  LOG_STACK: single
  MAIL_FROM_ADDRESS: '"hello@example.com"'
  MAIL_FROM_NAME: '"${APP_NAME}"'
  MAIL_HOST: 127.0.0.1
  MAIL_MAILER: log
  MAIL_PASSWORD: "null"
  MAIL_PORT: "2525"
  MAIL_SCHEME: "null"
  MAIL_USERNAME: "null"
  MEMCACHED_HOST: 127.0.0.1
  PHP_CLI_SERVER_WORKERS: "4"
  QUEUE_CONNECTION: database
  REDIS_CLIENT: phpredis
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  SESSION_DOMAIN: "null"
  SESSION_DRIVER: database
  SESSION_ENCRYPT: "false"
  SESSION_LIFETIME: "120"
  SESSION_PATH: /
  VITE_APP_NAME: '"${APP_NAME}"'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: env-cfm
