apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: meetup-route
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`meetup.mu`)
    services:
    - name: meetups-svc
      port: 8000
  tls:
    certResolver: le
